### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by eddymison** [Sylvan86/autoit-json-udf#2]
I downloaded the latest UDF and got the below errors:

Error 1:
"C:\Users\xxx\Desktop\j.au3" (81) : ==> Variable subscript badly formatted.:
Local $o_Current[]
Local $o_Current[^ ERROR

Error 2:
"C:\Users\xxx\Desktop\j.au3" (81) : ==> No variable given for "Dim", "Local", "Global", "Struct" or "Const" statement.:
Local Local $o_Current[] = ObjCreate("Scripting.Dictionary")
Local ^ ERROR

I've made the edits below using the code from the old version:
Error 1 fix:
Line 81:
From: Local $o_Current[]
To: Local $o_Current[] = ObjCreate("Scripting.Dictionary")

Error 2 fix:
Line 98: 
From: $o_Current[$s_Key] = $o_Value     ; add key:value to map
To: $o_Current($s_Key) = $o_Value     ; add key:value to map

I'm very new to GitHub so I don't know if there is another way to report these bugs.

**Comment by Sylvan86** [comment]
Without code that reproduces the error, it is of course only a guess:

The JSON UDF uses the AutoIt structure "Maps" to map objects. These were only added in newer versions of AutoIt.
So use a recent version of AutoIt.

For versions prior to this, there is still the "JSON_Dictionary.au3", which uses the Scripting.Dictionary object to map JSON objects. However, the development of this version is frozen - newer features are only available in JSON.au3.

This is therefore not a bug.

**Comment by Sylvan86** [comment]
Not a bug - no fix needed
